#!/usr/bin/sh

# DTESTING è per passare al cmake se stiamo testando o no
# non è un flag builtin di cmake, viene passato allo script così posso usarlo
# per avere la logica di test e compilazione normale in un singolo file
# questo evita molti più problemi di quanti ne crei
cmake -DTESTING="no"\
      -S . -B build/ 

cmake --build build/
